### ISSUE TITLE
Refactor customization config to use key:value

### ISSUE THREAD

**Issue by davidferlay** [launchrctl/web#145]
## Observed

- Customization variable keys are set in local config file but values are fetched from set group_vars yaml file
- This behavior works well in Ansible based projects using group_vars but does not apply so well to others

![Image](https://github.com/user-attachments/assets/f6481b6a-d5d3-494b-b2a4-f99c3a7fd3ae)

## Expected

- It would be great to simplify customization settings by using a key:value mechanism : 
```
web:
  vars_file: platform/group_vars/platform/vars.yaml
  variables:
    - plasmactl_web_ui_platform_name: "ABC"
```
